# version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: anakgantar123
      MYSQL_DATABASE: db-siswa
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: daniar17/siswa-api:latest
    container_name: golang-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    # volumes:
    #   - .:/app
    # command: ["./main"]

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

volumes:
  db_data:
  jenkins_home:
